title: TK Vesterålen
description: Jekyll microtheme that looks like JSON
baseurl: /
url: https://tkVesteraalen.no

#theme: hacked-jekyll
remote_theme: hydecorp/hydejack@v9

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never