title: TK Vesterålen
baseurl: /
url: https://tkVesteraalen.no

remote_theme: piazzai/hacked-jekyll
plugins:
- jekyll-remote-theme

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
