title: TK Vesterålen
description: Jekyll microtheme that looks like JSON
baseurl: /docs
url: https://tkVesteraalen.no

#theme: hacked-jekyll
#remote_theme: hydecorp/hydejack@v9
remote_theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never